apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aiot 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: project/argocd/aiot-manifests
    repoURL: https://github.com/htwalid/aiot-cicd
    targetRevision: HEAD
  syncPolicy: {}