apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: aiot 
data:
  mosquitto.conf: |-
    # Use "log_dest none" if you wish to disable logging.
    log_dest stdout
    
    # Port to use for the default listener.
    listener 9001
    listener 1883
    
    # Allow anonymous users to connect?
    # If not, the password file should be created
    allow_anonymous true

    # Choose the protocol to use when listening.
    # This can be either mqtt or websockets.
    # Certificate based TLS may be used with websockets, except that only the
    # cafile, certfile, keyfile, ciphers, and ciphers_tls13 options are supported.
    protocol mqtt
    
    # The password file.
    # Use the `mosquitto_passwd` utility.
    # If TLS is not compiled, plaintext "username:password" lines bay be used
    # password_file /mosquitto/config/passwd